# Generated by Django 3.2.9 on 2021-12-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211130_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbookuser',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
