# Generated by Django 3.2.9 on 2021-12-03 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0004_auto_20211202_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbookuser',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_book_user_book', to='myapp.book'),
        ),
        migrations.AlterField(
            model_name='orderbookuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_book_user_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
