# Generated by Django 3.2.9 on 2021-12-09 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveSmallIntegerField(choices=[('однокомнатная', 1), ('дыухкомнатная', 2), ('трехкомнатная', 3)], db_index=True, verbose_name='коллучуство комнат')),
                ('price_for_day', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='цена за день')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('number', models.PositiveSmallIntegerField(db_index=True, verbose_name='номер')),
                ('condition', models.BooleanField(default=False, verbose_name='кондиционер')),
                ('image', models.ImageField(upload_to='room/%Y', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='OrderRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='цена')),
                ('start_date', models.DateTimeField(verbose_name='дата заселения')),
                ('end_date', models.DateTimeField(verbose_name='дата выселения')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата заказа')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room', verbose_name='Комната')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='заказчик')),
            ],
            options={
                'verbose_name': 'бронь',
                'verbose_name_plural': 'брони',
            },
        ),
    ]
